# ÖNCELİKLE MERHABA HEPİNİZE ŞUNU SÖYLEMEM GEREKİYOR BEN BİLGİSAYARI DAHA DOĞRUSU TEKNOLOJİYİ SEVEN VE KULLANAN BİRİSİYMDİR BİLİYORUM
# BU İŞTE HENÜZ YENİ BİR BİREYİM HEVESİM VAR YAKLAŞIK 10 AYDIR KENDİM ÇALIŞIYORUM VE İNTERNET ÜZERİNDEN KENDİM ÖĞRENDİM BİRŞEYLER YAPMAYA ÇALIŞIYORUM
# BU YÜZDEN BİRÇOK KONUDA EKSİĞİM VAR VE BU EKSİKLERİMİ GİDERMEK İÇİN BURADAYIM
# BU YÜZDEN BANA YARDIMCI OLABİLECEK KİMSELERE İHTİYACIM VAR
# BENİMLE İLETİŞİME GEÇMEK İSTİYORSANIZ BANA BURADAN ULAŞABİLİRSİNİZ
# ŞİMDİDEN TEŞEKKÜR EDERİM
# İYİ ÇALIŞMALAR DİLERİM VE İYİ BAYRAMLAR DİLERİM
# VE BİRYERDEN BAŞLAMAK İSTİYORUM
# ŞİMDİDEN TEŞEKKÜR EDERİM
# İYİKİ VARSINIZ
